BartenderApp.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BartenderApp.Domain.Abstract;
using BartenderApp.Domain.Entities;

namespace BartenderApp.WebUI.Controllers
{
    public class AdminController : Controller
    {
        private IProductRepository repository;

        public AdminController (IProductRepository repo)
        {
            repository = repo;
        }
        
        public ActionResult Index()
        {
            return View(repository.Products);
        }

        public ViewResult Edit(int productID)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productID);
            return View(product);
        }

        [HttpPost]
        public ActionResult Edit (Product product)
        {
            if (ModelState.IsValid)
            {
                repository.SaveProduct(product);
                TempData["message"] = string.Format("{0} has been saved", product.Name);
                return RedirectToAction("Index");
            }else
            {
                return View(product);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Product());
        }

        [HttpPost]
        public ActionResult Delete(int productID)
        {
            Product deletedProduct = repository.DeleteProduct(productID);
            if (deletedProduct != null)
            {
                TempData["message"] = string.Format("{0} was deleted.", deletedProduct.Name);
            }
            return RedirectToAction("Index");
        }

    }
}

BartenderApp.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BartenderApp.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BartenderApp.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BartenderApp.Domain.Abstract;
using BartenderApp.Domain.Entities;
using BartenderApp.WebUI.Models;

namespace BartenderApp.WebUI.Controllers
{
    public class ProductController : Controller
    {
       private IProductRepository repository;
        public int PageSize = 4;

        public ProductController(IProductRepository productRepository)
        {
            this.repository = productRepository;
        }

        public ViewResult List(string category, int page = 1)
        {
            ProductListViewModel model = new ProductListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                        repository.Products.Count() :
                        repository.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
    }
}

BartenderApp.WebUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BartenderApp.WebUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BartenderApp.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1></h1>
    <p class="lead">Welcome to Morrison's authenic Irish Pub.</p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Order A Drink</h2>
        <p>
            Use this friendly form to enter your drink request.  The drinks will be loaded into the queue, and the bartender
            will fulfill the drink requests in the order they are recieved.  For special requests, not listed on the menu,
            feel free to ask any our our fabulous bartending staff to accommodate your wishes.
        </p>
        @Html.ActionLink("View the Menu", "List","Product", null,
                new { @class = "btn btn-block btn-default btn-long" })
    </div>
    <div class="col-md-6">
        <h2>Bartender Access</h2>
        <p>Bartenders may access the menu, make corrections, add products, and delete products from the drink menu. Bartenders can
        also add custom drinks to our menu and change prices to create specials. </p>
        @Html.ActionLink("Edit the Menu", "Index", "Admin", null,
                new { @class = "btn btn-block btn-default btn-long" })
    </div>

</div>